definitions:
  image_defaults: &image_defaults
    working_directory: ~/repo
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm

version: 2
jobs:
  checkout_install:
    <<: *image_defaults
    steps:
      - checkout
      - run: yarn global add @percy/agent lerna
      - run: yarn bootstrap --frozen-lockfile --non-interactive
      - run: npm rebuild node-sass
      - run: yarn cypress:verify
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - repo
            - .yarn

  lint:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint all Libraries
          command: yarn lint:all

  test_icons:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test icons library
          command: yarn ci:test:icons
      - run:
          name: Clear Git changed files
          command: git checkout -- .

  test_core_percy:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn bootstrap
      - run:
          name: Test core library with Percy.io snapshots
          command: yarn ci:test:core:percy
      - store_artifacts:
          path: ~/repo/core/cypress/
      - store_artifacts:
          path: ~/repo/core/dist/
      - run:
          name: Clear Git changed files
          command: git checkout -- .

  test_angularjs:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn bootstrap
      - run:
          name: Test angularjs library with Percy.io snapshots
          command: yarn ci:test:angularjs:percy
      - store_artifacts:
          path: ~/repo/angularjs/cypress/
      - store_artifacts:
          path: ~/repo/angularjs/dist/
      - run:
          name: Clear Git changed files
          command: git checkout -- .

  test_angular:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Test angular library
          command: yarn ci:test:angular
      - run:
          name: Clear Git changed files
          command: git checkout -- .

  test_react:
    <<: *image_defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn bootstrap
      - run:
          name: Unit Test react library
          command: yarn ci:test:react
      - run:
          name: Visual regression test react library with Percy.io snapshots
          command: yarn ci:test:react:percy
      - run:
          name: Clear Git changed files
          command: git checkout -- .

  percy_finalize_all:
    working_directory: ~/repo
    docker:
      - image: percyio/agent:latest
    steps:
      - attach_workspace:
          at: ~/
      - run: PERCY_TOKEN=$PERCY_TOKEN percy finalize --all

  lint_test_release:
    <<: *image_defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn global add @percy/agent lerna && yarn install --frozen-lockfile --non-interactive
      - run: yarn bootstrap
      - run: npm rebuild node-sass
      - run: yarn cypress:verify
      - run:
          name: Lint all Libraries
          command: yarn lint:all
      - run: yarn build:react
      - run:
          name: Test icons library
          command: yarn ci:test:icons
      - run:
          name: Test core library
          command: yarn ci:test:core
      - run:
          name: Test react library
          command: yarn ci:test:react
      - run:
          name: Test angular library
          command: yarn ci:test:angular
      - run:
          name: Clear Git changed files
          command: git checkout -- .
      - add_ssh_keys:
          fingerprints:
            - "8d:03:46:48:16:a2:7f:d4:97:2f:20:a1:fe:0e:81:35"
      - run:
          name: Configure git defaults
          command: git config user.email $GH_EMAIL && git config user.name $GH_USER
      - run: echo "registry=https://registry.npmjs.org" > ~/.npmrc
      - run: echo "registry \"https://registry.npmjs.org\"" > ~/.yarnrc
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: git status
      - run:
          name: Publish Releases
          command: yarn release
      - run:
          name: Update examples
          command: yarn data

workflows:
  version: 2
  lint_test:
    jobs:
      - checkout_install
      - lint:
          requires:
            - checkout_install
      - test_icons:
          requires:
            - lint
      - test_core_percy:
          requires:
            - lint
      - test_angularjs:
          requires:
            - lint
      - test_react:
          requires:
            - lint
      - test_angular:
          requires:
            - lint
      - percy_finalize_all:
          requires:
            - test_icons
            - test_core_percy
            - test_react
            - test_angular
            - test_angularjs

  daily_release:
    triggers:
      - schedule:
          cron: "30 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint_test_release

